% 批量替换 Denovo_AUPR_mean = R_m_A_AUPR_value
fileList = {
    'CTDdataset2023_STresult_BNNR_Denovoone.mat',...
    'CTDdataset2023_STresult_DDASKF_Denovoone.mat',...
    'CTDdataset2023_STresult_HGIMC_Denovoone.mat',...
    'CTDdataset2023_STresult_MBiRW_Denovoone.mat',...
    'CTDdataset2023_STresult_MSBMF_Denovoone.mat',...
    'CTDdataset2023_STresult_multiGMF_Denovoone.mat',...
    'Cdataset_STresult_BNNR_Denovoone.mat',...
    'Cdataset_STresult_DDASKF_Denovoone.mat',...
    'Cdataset_STresult_HGIMC_Denovoone.mat',...
    'Cdataset_STresult_MBiRW_Denovoone.mat',...
    'Cdataset_STresult_MSBMF_Denovoone.mat',...
    'Cdataset_STresult_multiGMF_Denovoone.mat',...
    'Fdataset_STresult_BNNR_Denovoone.mat',...
    'Fdataset_STresult_DDASKF_Denovoone.mat',...
    'Fdataset_STresult_HGIMC_Denovoone.mat',...
    'Fdataset_STresult_MBiRW_Denovoone.mat',...
    'Fdataset_STresult_MSBMF_Denovoone.mat',...
    'Fdataset_STresult_multiGMF_Denovoone.mat'
};

for i = 1:length(fileList)
    fname = fileList{i};
    fprintf('正在处理：%s\n', fname);
    
    % 加载文件所有变量
    data = load(fname);
    
    % 替换：Denovo_AUPR_mean = R_m_A_AUPR_value
    if isfield(data, 'R_m_A_AUPR_value')
        data.Denovo_AUPR_mean = data.R_m_A_AUPR_value;
    else
        fprintf('  警告：%s 中不存在 R_m_A_AUPR_value，跳过\n', fname);
        continue;
    end
    
    % 获取文件中所有变量名并保存
    varNames = fieldnames(data);
    save(fname, '-struct', 'data', varNames{:}, '-v7.3');
end

fprintf('全部文件处理完成！\n');